### PR TITLE
chore: move react + prop-types to peerDeps

### PR DESCRIPTION
**Pull request by probablyup**
Also loosened the versioning to make future updates easier.

### CODE REVIEW

**Comment by probablyup** [comment]
As a side effect, this should help fix tools like https://cost-of-modules.herokuapp.com/ from reporting `theming` from being larger than it really is 😄

**Comment by probablyup** [comment]
Not sure why the coverage dropped - no code changes 🤷🏼‍♂️

**Comment by jgoux** [comment]
I hope this PR will be merged soon. This is blocking my upgrade to React 16, because react-jss depends on this library. :(

**Comment by philpl** [comment]
@jgoux FYI in the meantime you can add aliases for React and prop-types to Webpack to point to their node_modules folder directly. That’ll replace the npm resolution with the one fixed version you are pointing to

**Comment by jgoux** [comment]
@philpl Didn't even think about it!
Thanks for the tip, it will do for now. ✨

**Comment by kof** [comment]
we need to update to v16

**Pull request closed without merging**
