### PR TITLE
Added unsubscribe to the theme listener

### PR DESCRIPTION
**Pull request by TriPSs**
Added the unsubscribe function so we can unsubscribe from the theme-listener in `react-jss`

This PR goes together with [react-jss - 187](https://github.com/cssinjs/react-jss/pull/187)

### CODE REVIEW

**Comment by kof** [comment]
thanks!

**Comment by kof** [comment]
Damn, just realized, subscribe function returns an unsubscribe function, there is no need in separate unsubscribe function. Why??????

**Comment by TriPSs** [comment]
Because I logged it and the only thing I got back was an ID

**Comment by kof** [comment]
Wow, true, turns out brcast library has changed!

**Comment by kof** [comment]
And the reason was  a performance optimization.

**Pull request merged**
